/**
 * \file itlp.h
 * \brief Header file for all the publicly available functions available in libitlp
 * \author Jean THOMAS <itlp@jeanthomas.me>
 */

#include <stdint.h>

#include "itlp/types.h"

/**
 * @fn struct msdh** itlp_open_library(char *library_file)
 * @param library_file Path to the library file
 * 
 * Parses a library into a msdh block array
 */
struct msdh** itlp_open_library(char *library_file);

/**
 * @fn void itlp_free(struct msdh **msdh_array)
 * @param msdh_array msdh block array to be freed
 *
 * Frees an array of msdh blocks, ie. generated by itlp_open_library().
 */
void itlp_free(struct msdh **msdh_array);
